#!/usr/bin/env bash
# video-stream installer — one script for the whole studio.
#
#   ./install.sh              core install, then asks about each add-on
#   ./install.sh --all        core + pose + avatar + phone, no questions
#   ./install.sh --core-only  just the rig (lightest install)
#   ./install.sh --pose --avatar --phone   pick add-ons explicitly
#
# Add-ons (each also has its own script, still usable directly):
#   pose    MediaPipe skeleton overlay + face-aware auto punch-ins
#   avatar  VTuber avatar studio (vendored three-vrm + face models)
#   phone   phone-as-camera HTTPS certificate (needs openssl)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV="${ROOT}/.venv"
BIN_DIR="${HOME}/.local/bin"
LAUNCHER="${BIN_DIR}/video-stream"
PYTHON_BIN="${VENV}/bin/python"

bold() { printf '\033[1m%s\033[0m\n' "$*"; }
ok()   { printf '  \033[32m✓\033[0m %s\n' "$*"; }
warn() { printf '  \033[33m!\033[0m %s\n' "$*"; }
info() { printf '  → %s\n' "$*"; }
die()  { printf '\033[31merror:\033[0m %s\n' "$*" >&2; exit 1; }

# ── Add-on selection ───────────────────────────────────
WANT_POSE=""
WANT_AVATAR=""
WANT_PHONE=""
ASKED=0
for arg in "$@"; do
  case "${arg}" in
    --all)       WANT_POSE=1; WANT_AVATAR=1; WANT_PHONE=1; ASKED=1 ;;
    --core-only) ASKED=1 ;;
    --pose)      WANT_POSE=1; ASKED=1 ;;
    --avatar)    WANT_AVATAR=1; ASKED=1 ;;
    --phone)     WANT_PHONE=1; ASKED=1 ;;
    -h|--help)   sed -n '2,12p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) die "unknown option: ${arg} (try --help)" ;;
  esac
done

bold "video-stream · install"
echo

OS="$(uname -s)"

# ── Python ─────────────────────────────────────────────
if ! command -v python3 >/dev/null 2>&1; then
  die "python3 not found. Install Python 3.10+ and re-run."
fi

# ── Linux camera preflight ─────────────────────────────
# Both of these fail *silently* at runtime: the dashboard simply lists no
# cameras, with nothing to indicate why. Warn here instead.
if [[ "${OS}" == "Linux" ]]; then
  if ! python3 -c 'import venv' 2>/dev/null; then
    die "Python venv module missing. Install it (Debian/Ubuntu: apt install python3-venv) and re-run."
  fi

  shopt -s nullglob
  VIDEO_NODES=(/dev/video*)
  shopt -u nullglob

  if (( ${#VIDEO_NODES[@]} == 0 )); then
    warn "No /dev/video* devices found — no cameras are currently attached."
    info "Plug a camera in and re-run, or continue and use Rescan in the dashboard later."
  else
    ok "found ${#VIDEO_NODES[@]} /dev/video* node(s)"
  fi

  if ! id -nG "$(id -un)" 2>/dev/null | tr ' ' '\n' | grep -qx video; then
    warn "$(id -un) is not in the 'video' group — cameras will not open."
    info "Fix with:  sudo usermod -aG video $(id -un)"
    info "Then log out and back in (group changes need a fresh session)."
  else
    ok "user is in the 'video' group"
  fi
fi

PY_VER="$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')"
python3 -c 'import sys; raise SystemExit(0 if sys.version_info >= (3, 10) else 1)' \
  || die "Python 3.10+ required (found ${PY_VER})"
ok "Python ${PY_VER}"

# ── Virtualenv ─────────────────────────────────────────
if [[ ! -x "${PYTHON_BIN}" ]]; then
  info "Creating virtualenv at .venv"
  python3 -m venv "${VENV}"
else
  info "Reusing existing .venv"
fi
ok "venv ready"

# ── Dependencies ───────────────────────────────────────
info "Installing packages (editable)"
# shellcheck disable=SC1091
source "${VENV}/bin/activate"
python -m pip install --upgrade pip -q
python -m pip install -e "${ROOT}" -q
ok "dependencies installed"

# ── Launcher on PATH ───────────────────────────────────
mkdir -p "${BIN_DIR}"

cat > "${LAUNCHER}" <<EOF
#!/usr/bin/env bash
# Auto-generated by video-stream install.sh — do not edit by hand
set -euo pipefail
ROOT="${ROOT}"
VENV="\${ROOT}/.venv"
PYTHON="\${VENV}/bin/python"

if [[ ! -x "\${PYTHON}" ]]; then
  echo "video-stream is not installed correctly." >&2
  echo "Run:  cd \${ROOT} && ./install.sh" >&2
  exit 1
fi

export PYTHONPATH="\${ROOT}\${PYTHONPATH:+:\${PYTHONPATH}}"
exec "\${PYTHON}" -m video_stream "\$@"
EOF

chmod +x "${LAUNCHER}"
ok "command installed → ${LAUNCHER}"

# ── PATH check ─────────────────────────────────────────
case ":${PATH}:" in
  *":${BIN_DIR}:"*) ok "~/.local/bin already on PATH" ;;
  *)
    SHELL_NAME="$(basename "${SHELL:-bash}")"
    RC=""
    case "${SHELL_NAME}" in
      zsh)  RC="${HOME}/.zshrc" ;;
      bash) RC="${HOME}/.bashrc" ;;
      *)    RC="${HOME}/.profile" ;;
    esac

    LINE='export PATH="$HOME/.local/bin:$PATH"'
    if [[ -f "${RC}" ]] && grep -Fq '.local/bin' "${RC}" 2>/dev/null; then
      ok "PATH snippet already present in ${RC}"
    else
      info "Adding ~/.local/bin to PATH in ${RC}"
      {
        echo ""
        echo "# video-stream (and other user commands)"
        echo "${LINE}"
      } >> "${RC}"
      ok "updated ${RC}"
    fi
    # Make available in this shell session when sourced
    export PATH="${BIN_DIR}:${PATH}"
    echo
    info "Open a new terminal, or run:  source ${RC}"
    ;;
esac

# ── Add-ons ────────────────────────────────────────────
# Interactive runs get asked (Enter = yes → the full studio); flags or
# non-interactive runs (curl | bash, CI) skip prompts.
if [[ "${ASKED}" == 0 && -t 0 ]]; then
  echo
  bold "Optional add-ons"
  read -r -p "  Pose tracking — skeleton overlay + face-aware punch-ins? [Y/n] " a || a=""
  [[ "${a}" =~ ^[Nn] ]] || WANT_POSE=1
  read -r -p "  Avatar studio — VTuber avatars driven by your face? [Y/n] " a || a=""
  [[ "${a}" =~ ^[Nn] ]] || WANT_AVATAR=1
  read -r -p "  Phone as camera — HTTPS cert so phones can join by QR? [Y/n] " a || a=""
  [[ "${a}" =~ ^[Nn] ]] || WANT_PHONE=1
elif [[ "${ASKED}" == 0 ]]; then
  info "non-interactive run: core only (add later with ./install.sh --all)"
fi

echo
if [[ -n "${WANT_POSE}" ]]; then
  bash "${ROOT}/install-pose.sh" || warn "pose add-on failed — re-run ./install-pose.sh later"
fi
if [[ -n "${WANT_AVATAR}" ]]; then
  bash "${ROOT}/install-avatar.sh" || warn "avatar add-on failed — re-run ./install-avatar.sh later"
fi
if [[ -n "${WANT_PHONE}" ]]; then
  if command -v openssl >/dev/null 2>&1; then
    bash "${ROOT}/install-phone.sh" || warn "phone add-on failed — re-run ./install-phone.sh later"
  else
    warn "openssl not found — skipping the phone certificate (install openssl, then ./install-phone.sh)"
  fi
fi

# ── Smoke check ────────────────────────────────────────
# Import every module once so a broken install fails HERE, loudly,
# instead of at showtime.
if "${PYTHON_BIN}" - <<'PY' 2>/dev/null
import video_stream.app  # pulls in camera/director/hub/safety/replay/overlays/chat/settings/wizard/peers/phone/chaos
PY
then
  ok "all studio modules import cleanly"
else
  warn "module import failed — try removing .venv and re-running ./install.sh"
fi

echo
bold "Done."
echo
echo "  Start anytime with:"
echo "    video-stream"
echo
echo "  That starts the server and opens the dashboard — cameras with"
echo "  copyable OBS URLs, the auto-director, replay highlights, Smart"
echo "  Zoom, live captions, overlays, unified chat, chaos FX, and the"
echo "  Setup wizard (scan → propose a scene map → verify the rig)."
echo
echo "  Extra flags:  video-stream --port 9000 --no-open"
echo "                video-stream --director --director-rules rules.json"
echo "                video-stream --director --peers \"studio=<ip>:8765\"   (Rig Link)"
echo
MISSING=""
[[ -z "${WANT_POSE}" ]] && MISSING="${MISSING}    --pose      skeleton overlay + face-aware auto punch-ins\n"
[[ -z "${WANT_AVATAR}" ]] && MISSING="${MISSING}    --avatar    VTuber avatar studio (three-vrm + tracking)\n"
[[ -z "${WANT_PHONE}" ]] && MISSING="${MISSING}    --phone     phone-as-camera HTTPS certificate\n"
if [[ -n "${MISSING}" ]]; then
  echo "  Add-ons you skipped (get them anytime with ./install.sh <flag>):"
  printf "%b" "${MISSING}"
  echo
fi
echo "  OBS browser-source overlays (copy URLs from the dashboard):"
echo "    /overlay/subtitles  /overlay/hud  /overlay/alerts"
echo "    /overlay/stinger    /overlay/chat  /overlay/fx"
echo
echo "  Re-run this installer anytime to refresh the install."
echo
