#!/usr/bin/env bash
# video-stream installer — venv + global `video-stream` command
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV="${ROOT}/.venv"
BIN_DIR="${HOME}/.local/bin"
LAUNCHER="${BIN_DIR}/video-stream"
PYTHON_BIN="${VENV}/bin/python"

bold() { printf '\033[1m%s\033[0m\n' "$*"; }
ok()   { printf '  \033[32m✓\033[0m %s\n' "$*"; }
info() { printf '  → %s\n' "$*"; }
die()  { printf '\033[31merror:\033[0m %s\n' "$*" >&2; exit 1; }

bold "video-stream · install"
echo

# ── Python ─────────────────────────────────────────────
if ! command -v python3 >/dev/null 2>&1; then
  die "python3 not found. Install Python 3.10+ and re-run."
fi

PY_VER="$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')"
python3 -c 'import sys; raise SystemExit(0 if sys.version_info >= (3, 10) else 1)' \
  || die "Python 3.10+ required (found ${PY_VER})"
ok "Python ${PY_VER}"

# ── Virtualenv ─────────────────────────────────────────
if [[ ! -x "${PYTHON_BIN}" ]]; then
  info "Creating virtualenv at .venv"
  python3 -m venv "${VENV}"
else
  info "Reusing existing .venv"
fi
ok "venv ready"

# ── Dependencies ───────────────────────────────────────
info "Installing packages (editable)"
# shellcheck disable=SC1091
source "${VENV}/bin/activate"
python -m pip install --upgrade pip -q
python -m pip install -e "${ROOT}" -q
ok "dependencies installed"

# ── Launcher on PATH ───────────────────────────────────
mkdir -p "${BIN_DIR}"

cat > "${LAUNCHER}" <<EOF
#!/usr/bin/env bash
# Auto-generated by video-stream install.sh — do not edit by hand
set -euo pipefail
ROOT="${ROOT}"
VENV="\${ROOT}/.venv"
PYTHON="\${VENV}/bin/python"

if [[ ! -x "\${PYTHON}" ]]; then
  echo "video-stream is not installed correctly." >&2
  echo "Run:  cd \${ROOT} && ./install.sh" >&2
  exit 1
fi

export PYTHONPATH="\${ROOT}\${PYTHONPATH:+:\${PYTHONPATH}}"
exec "\${PYTHON}" -m video_stream "\$@"
EOF

chmod +x "${LAUNCHER}"
ok "command installed → ${LAUNCHER}"

# ── PATH check ─────────────────────────────────────────
case ":${PATH}:" in
  *":${BIN_DIR}:"*) ok "~/.local/bin already on PATH" ;;
  *)
    SHELL_NAME="$(basename "${SHELL:-bash}")"
    RC=""
    case "${SHELL_NAME}" in
      zsh)  RC="${HOME}/.zshrc" ;;
      bash) RC="${HOME}/.bashrc" ;;
      *)    RC="${HOME}/.profile" ;;
    esac

    LINE='export PATH="$HOME/.local/bin:$PATH"'
    if [[ -f "${RC}" ]] && grep -Fq '.local/bin' "${RC}" 2>/dev/null; then
      ok "PATH snippet already present in ${RC}"
    else
      info "Adding ~/.local/bin to PATH in ${RC}"
      {
        echo ""
        echo "# video-stream (and other user commands)"
        echo "${LINE}"
      } >> "${RC}"
      ok "updated ${RC}"
    fi
    # Make available in this shell session when sourced
    export PATH="${BIN_DIR}:${PATH}"
    echo
    info "Open a new terminal, or run:  source ${RC}"
    ;;
esac

echo
bold "Done."
echo
echo "  Start anytime with:"
echo "    video-stream"
echo
echo "  That will start the server and open the dashboard."
echo "  Extra flags work too:  video-stream --port 9000 --no-open"
echo
echo "  Re-run this installer anytime to refresh the install."
echo
